version: '3.1'

services: 


    php: 
        build: 
            context: ./.build/docker/php
            dockerfile: Dockerfile
        volumes: 
            - ./:/app
        ports: 
            - "80:8080"